config/routes.rb
Rails.application.routes.draw do

  root :to => 'public/homes#top'

devise_for :users, controllers: {
  sessions: 'user/sessions',
  registrations: 'user/registrations'
}


namespace :public, path: "" do
  get 'users/mypage' => 'users#mypage'
  get'posts_all' => 'posts#posts_all'
  post'posts_all' => 'posts#posts_all'
  get 'search_all' => 'users#search_all'
  post 'search_all' => 'users#search_all'
  resources :users, only: [:edit, :update ,:index , :show] do
    resources :posts, only: [:index,:create,:show,:edit,:update, :destroy] do
    delete 'post_item_destroy'
    post 'post_item_create'
    resources :post_items, only: [:destroy,:show]
    resources :likes, only: [:create, :destroy, :index]
    resources :comments, only: [:create, :destroy]
  end
    get 'unsubscribe' => 'users#unsubscribe', as: 'confirm_unsubscribe'
    patch 'withdraw' => 'users#withdraw', as: 'withdraw_user'
    put 'withdraw' => 'users#withdraw'
    get 'users/tags' => 'posts#post_tags'
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    resource :favorites, only: [:create, :destroy]
  end
  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show, :index]
  end

  devise_for :admins, controllers: {
  sessions: 'user/sessions',
  registrations: 'user/registrations'
}




namespace :admins do
  resources :users
  resources :posts
  patch 'post_item_update' => 'posts#post_item_update'
  resources :tags, only: [:index]
end

end

app/models/user.rb
class User < ApplicationRecord
  enum is_active: { E: 0, F: 1, G: 2, H: 3 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  attachment :image
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 【class_name: "Relationship"】は省略可能
  has_many :followings, through: :relationships, source: :followed
  # 与フォロー関係を通じて参照→follower_idをフォローしている人3

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy



  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end

  def full_name
    first_name + last_name
  end



  def full_name_kana
    first_name_kana + last_name_kana
  end

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

  def active_for_authentication?
    super && (self.is_active == "E")
  end

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController

  def index
    @users = User.all.order("id DESC").page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end



  def update
    @user = User.find(params[:id])
    if  @user.update(users_params)
      redirect_to admins_user_path(@user.id)
    else
      render :edit
    end
  end
  
  protected

  def users_params
    params.require(:user).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :phone_number, :is_active ,:image,:instagram_id,
    :introduction)
  end

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # GET /resource/cheak
  # def show
  #   super
  # end



  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

   #The path used after sign up for inactive accounts.
   def after_inactive_sign_up_path_for(resource)
      public_users_mypage_path(resource)
   end



end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/views/admins/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <%= form_with model: @user,url:  admins_user_path(@user.id), local: true do |f| %>
        <div class="sign_up_all m-4">
          <h4 class="text-center">ユーザー編集</h4>
            <div class="sign_up_item  mx-auto m-4" style="width:60%;">
              <div class="sign_up_name m-2">
                <p class="my-3">名前</p>
                <div class="d-flex justify-content-between">
                  <p>姓　　<%= f.text_field :first_name %></p>
                  <p>名　<%= f.text_field :last_name %></p>
                </div>
              </div>
              <div class="sign_up_name_kana m-2">
                <p class="my-3">名前（カナ）</p>
                  <div class="d-flex justify-content-between">
                    <p>セイ　<%= f.text_field :first_name_kana %></p>
                    <p>メイ　<%= f.text_field :last_name_kana %></p>
                  </div>
              </div>
              <div class="user-image d-flex justify-content-between m-3">
                <p>ユーザー画像</p>
                <div><%= f.attachment_field :image %></div>
              </div>
              <div class="email d-flex justify-content-between m-3">
                <p>メールアドレス</p>
                <p><%= f.text_field :email %></p>
              </div>
              <div class="phone_number d-flex justify-content-between m-3">
                <p>電話番号</p>
                <p><%= f.text_field :phone_number %></p>
              </div>
              <div class="users-image d-flex justify-content-between m-3">
                 <p>インスタグラムID</p>
                 <p><%= f.text_field :instagram_id %></p>
              </div>
              <div class="user-introduction d-flex justify-content-between m-3">
                <p>自己紹介</p>
                <p><%= f.text_area :introduction %></p>
              </div>
              <div class="user-is_active d-flex justify-content-around m-3">
                <div>
                  <%= f.radio_button :is_active, 'E', checked: true %>
                  <%= f.label :is_active, "登録中" %>
                </div>
                <div>
                  <%= f.radio_button :is_active, 'F'  %>
                  <%= f.label :ranki, "退会済み" %>
                </div>
              </div>
                <div class="submit text-center">
                  <%= f.submit '決定する', class: "btn btn-primary text-white" %>
                </div>
            </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="user-all">
        <div class="user-title">
          <h4 class="mb-5 text-center">ユーザー一覧</h4>
        </div>
        <table class="table">
          <thead>
            <tr>
              <th>ユーザーネーム</th>
              <th>ユーザー画像</th>
              <th>投稿数</th>
              <th>フォロー数</th>
              <th>フォロワー数</th>
              <th>ユーザーステータス</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.full_name %></td>
              <td><%= attachment_image_tag user, :image, :fill, 60, 60 %></td>
              <td><%= user.posts.count %></td>
              <td><%= user.followings.count %></td>
              <td><%= user.followers.count %></td>
              <td>
                <% if user.is_active == "E" %>
                  <p class="text-success">登録済み</p>
                <% else user.is_active == "F" %>
                  <p class="text-success">退会済み</p>
                <% end %>
              </td>
              <td>
                <%= link_to 'ユーザー詳細へ',admins_user_path(user.id), class: "btn btn-success" %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
        <%= paginate @users %>
      </div>
    </div>
  </div>
</div>

app/views/admins/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="mypage">
        <div class="mypage-title text-center">
           <h4>マイページ</h4>
        </div>
        <div class="mypage-path text-center">
          <div class="name w-50 mx-auto">
            <div class="user-name p-2">
              <div class="font-weight-bold">名前</div>
              <div class="border-bottom  border-info"><%= @user.full_name %></div>
            </div>
            <div class="user-name-kana p-2">
              <div class="font-weight-bold">名前(カナ)</div>
              <div class="border-bottom  border-info"><%= @user.full_name_kana%></div>
            </div>
          </div>
        </div>
        <div class="user-mypage w-75 mx-auto m-4 text-center">
          <div class="profile-list">
            <div class="profile-image mx-auto w-75 text-center">
              <h4 class="m-4">ユーザー画像</h4>
              <%= image_tag attachment_url(@user, :image, :fill, 250, 250, format: "jpg",fallback: "user.jpeg") %>
            </div>
            <div class="user-path m-4">
              <div class="user-name p-2">
                <div class="font-weight-bold">電話番号</div>
                <div class="border-bottom  border-info"><%= @user.phone_number %></div>
              </div>
              <div class="user-instagram_id p-2">
                <div class="font-weight-bold">インスタグラムID</div>
                <div class="border-bottom  border-info"><%= @user.instagram_id%></div>
              </div>
              <div class="user-introduction p-2">
                <div class="font-weight-bold">自己紹介</div>
                <div class="border-bottom  border-info"><%= @user.introduction%></div>
              </div>
              <div class="user-introduction p-2">
                <div class="font-weight-bold">投稿数</div>
                <div class="border-bottom  border-info"><%=link_to @user.posts.count, public_user_posts_path(@user.id), class:"text-success"%></div>
              </div>
               <div class="user-introduction p-2">
                <div class="font-weight-bold">会員ステータス</div>
                <div class="border-bottom  border-info">
                  <% if @user.is_active == "E" %>
                    <p>登録済み</p>
                  <% else %>
                    <p>退会済み</p>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="user-item  text-center d-flex justify-content-center">
          <div class="user-all-link m-2">
            <%= link_to 'ユーザー一覧へ',admins_users_path,class: "btn btn-secondary" %>
          </div>
          <div class="user-item user-edit m-2">
            <%= link_to '編集する',  edit_admins_user_path(@user.id), class:"btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>