config/routes.rb
Rails.application.routes.draw do

  root :to => 'public/homes#top'

devise_for :users, controllers: {
  sessions: 'user/sessions',
  registrations: 'user/registrations'
}


namespace :public, path: "" do
  get 'users/mypage' => 'users#mypage'
  get'posts_all' => 'posts#posts_all'
  post'posts_all' => 'posts#posts_all'
  get 'search_all' => 'users#search_all'
  post 'search_all' => 'users#search_all'
  resources :users, only: [:edit, :update ,:index , :show] do
    resources :posts, only: [:index,:create,:show,:edit,:update, :destroy] do
    delete 'post_item_destroy'
    post 'post_item_create'
    resources :post_items, only: [:destroy,:show]
    resources :likes, only: [:create, :destroy, :index]
    resources :comments, only: [:create, :destroy]
  end
    get 'unsubscribe' => 'users#unsubscribe', as: 'confirm_unsubscribe'
    patch 'withdraw' => 'users#withdraw', as: 'withdraw_user'
    put 'withdraw' => 'users#withdraw'
    get 'users/tags' => 'posts#post_tags'
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    resource :favorites, only: [:create, :destroy]
  end
  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show, :index]
  end

  devise_for :admins, controllers: {
  sessions: 'user/sessions',
  registrations: 'user/registrations'
}




namespace :admins do
  resources :users
  resources :posts
  patch 'post_item_update' => 'posts#post_item_update'
  resources :tags, only: [:index]
end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/inquire.rb
class Inquire < ApplicationRecord
  belongs_to :user
  attr_accessor :name, :email, :message
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
  validates :message, presence: true
  belongs_to :user
  belongs_to :room
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_items,  dependent: :destroy
  acts_as_taggable   # acts_as_taggable_on :tags の省略
  acts_as_taggable_on :skills, :interests  # @post.skill_list とかが使えるようになる
  has_many :likes,  dependent: :destroy
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :post_items
  acts_as_taggable   # acts_as_taggable_on :tags の省略
# 参)複数設定も可能↓
  acts_as_taggable_on :skills, :interests  # @post.skil
  acts_as_taggable_on :tags, :skills


  def liked_by?(user)
    likes.where(user_id: user_id).exists?
  end




  def self.posts_all(posts_all)
    if posts_all
      Post.where('title LIKE ?', "%#{posts_all}%")
    else
      Post.all
    end
  end





  mount_uploaders :images, ImageUploader
  enum genre_name: { 寿司・魚料理: 0, 和食・日本料理: 1, ラーメン・麺類: 2, 丼もの・揚げ物: 3,
                    お好み焼き・粉物: 4, 郷土料理: 5, アジア・エスニック: 6, 中華: 7,
                    イタリアン: 8, 要職・西洋料理: 9,  フレンチ: 10,  アメリカ料理: 11,
                    アフリカ料理: 12,  珍しい各国料理: 13,  焼肉・ステーキ: 14,  焼き鳥・串料理: 15,
                    こだわり肉料理: 16,  鍋: 17,  しゃぶしゃぶ・すき焼き: 18,  居酒屋・バー: 19,
                    カフェ・スイーツ: 20,  ファミレス・ファストフード: 21, ピッフェ・バイキング: 22}
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :post
  attachment :image
end

app/models/post_item.rb
class PostItem < ApplicationRecord
  belongs_to :post
  mount_uploaders :images, ImageUploader
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/tag_map.rb
class TagMap < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  enum is_active: { E: 0, F: 1, G: 2, H: 3 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  attachment :image
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 【class_name: "Relationship"】は省略可能
  has_many :followings, through: :relationships, source: :followed
  # 与フォロー関係を通じて参照→follower_idをフォローしている人3

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy



  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end

  def full_name
    first_name + last_name
  end



  def full_name_kana
    first_name_kana + last_name_kana
  end

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

  def active_for_authentication?
    super && (self.is_active == "E")
  end

end

app/controllers/admins/tags_controller.rb
class Admins::TagsController < ApplicationController

  def index
     @tags = Post.tag_counts_on(:tags).order('count DESC').page(params[:page]).per(10)
     @posts = Post.all
  if @tag = params[:tag]   # タグ検索用
    @post = Post.tagged_with(params[:tag]).order(id: "DESC").page(1).per(10)   # タグに紐付く投稿
  end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   protect_from_forgery with: :exception
 before_action :configure_permitted_parameters, if: :devise_controller?

def after_sign_in_path_for(resource)
  case resource
  when User
    public_users_mypage_path
  when Admin
    admins_users_path
  end
end



  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin_admin_user
      new_admin_user_registaration_path
    else
      root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :phone_number, :is_active ,:image,:instagram_id,
    :introduction])
  end

end

app/helpers/admins/tags_helper.rb
module Admins::TagsHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entrys_helper.rb
module EntrysHelper
end

app/helpers/inquires_helper.rb
module InquiresHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/admins/tags/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="tag">
        <div class="tag-all">
          <h4 class="text-center mb-5">タグ一覧</h4>
        </div>
        <table class="table">
          <thead>
            <tr>
              <th>タグ名</th>
              <th>タグ数</th>
              <th>タグ編集</th>
            </tr>
          </thead>
          <tbody>
            <% @tags.each do |tag| %>
            <tr>
              <td><%= tag.name %></td>
              <td><%= tag.taggings_count %></td>
              <td><%=link_to '表示する',admins_tags_path(tag: tag.name) %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @tags %>
      </div>
      <%if @post.present? %>
        <div class="table-all">
          <h4 class="m-5 text-center">投稿一覧</h4>
          <table class= "table m-4">
             <thead>
               <tr>
                  <th>タイトル</th>
                  <th>ジャンル名</th>
                  <th>料理画像</th>
                  <th>いいね数</th>
                  <th>料理詳細</th>
               </tr>
              </thead>
              <tbody>
                <% @post.each do |post| %>
                  <tr>
                    <td><%= post.title %></td>
                    <td><%= post.genre_name %></td>
                    <td>
                      <% post.images.each do |post| %>
                        <%= image_tag (post.url),width: '30px', height: '30px' %>
                      <% end %>
                    </td>
                    <td><%= post.likes.count %></td>
                    <td><%= post.tag_list %></td>
                    <td>
                      <%= link_to '料理詳細へ',   admins_post_path(post.id) ,'data-turbolinks': false,class: "btn btn-success" %>
                    </td>
                  </tr>
                 <% end %>
              </tbody>
            </table>
          </div>
        <% end %>
    </div>
  </div>
</div>